management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.endpoint.logfile.enabled: true
management.endpoints.web.exposure.include: '*'

server:
  port: 8082
spring:
  application:
    name: notification-service
  boot:
    admin:
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        instance:
          metadata:
            tags:
              environment: localhost
          name: ${spring.application.name}
          prefer-ip: true
          service-base-url: http://localhost:8082
        url: http://localhost:9595

reloadly:
  auth:
    enabled: true
    reloadly-auth-service-endpoint: http://localhost:9090
  integration:
    sms:
      twilio:
        dry-run: ${TWILIO_DRY_RUN}
        messaging-service-id: ${TWILIO_MSG_SVC_ID}
        twilio-account-sid: ${TWILIO_ACCOUNT_SID}
        twilio-auth-token: ${TWILIO_AUTH_TOKEN}
    email:
      ses:
        enabled: true
        region: ap-south-1
        dry-run: ${EMAIL_DRY_RUN}
        from-email-id: ${SENDER_EMAIL_ID}
    swagger:
      enabled: true
      secured: true
      api-title: Reloadly Notification Services API
      api-description: Reloadly Notification Services API
      api-version: 1.1.0
      base-url: /
      host: localhost:8082
      base-package: com.reloadly.notification.controller
      api-terms-of-service-url: https://reloadly.com/termsofservice
      license: Copyright api.com
      license-url: https://reloadly.com/license
      contact:
        email: info@reloadly.com
        name: Reloadly Customer Service
        url: https://reloadly.com