management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.endpoint.logfile.enabled: true
management.endpoints.web.exposure.include: '*'

spring.kafka.bootstrap-servers: localhost:9092

server:
  port: 8081
spring:
  application:
    name: transaction-service
  datasource:
    continue-on-error: false
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 4
      pool-name: TxnSvcHikariPool
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    initialization-mode: never
    name: rltxndb
    platform: mysql
    url: jdbc:mysql://localhost:3306/rltxndb
    generate-unique-name: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
    show-sql: false
    open-in-view: false
  boot:
    admin:
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        instance:
          metadata:
            tags:
              environment: localhost
          name: ${spring.application.name}
          prefer-ip: true
          service-base-url: http://localhost:8081
        url: http://localhost:9595

reloadly:
  auth:
    enabled: true
    reloadly-auth-service-endpoint: http://localhost:9090
  integration:
    swagger:
      enabled: true
      secured: true
      api-title: Reloadly Transaction Services API
      api-description: Reloadly Transaction Services API
      api-version: 1.1.0
      base-url: /
      host: localhost:8081
      base-package: com.reloadly.transaction.controller
      api-terms-of-service-url: https://reloadly.com/termsofservice
      license: Copyright api.com
      license-url: https://reloadly.com/license
      contact:
        email: info@reloadly.com
        name: Reloadly Customer Service
        url: https://reloadly.com
  api:
    transaction:
      service:
        kafka:
          inbound-transactions-topic: com.reloadly.inbound.txn.topic
