apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  {{- if not .Values.reloadly.ingress.enabled }}
  type: {{ .Values.reloadly.transactionApp.service.type }}
  {{- end }}
  selector:
    app: transaction-service
  ports:
    - port: 8081
      targetPort: 8081
      {{- if not .Values.reloadly.ingress.enabled }}
      nodePort: 30081
      {{- end }}