apiVersion: v1
kind: Service
metadata:
  name: transaction-processor
spec:
  {{- if not .Values.reloadly.ingress.enabled }}
  type: {{ .Values.reloadly.transactionProcApp.service.type }}
  {{- end }}
  selector:
    app: transaction-processor
  ports:
    - port: 8083
      targetPort: 8083
      {{- if not .Values.reloadly.ingress.enabled }}
      nodePort: 30083
      {{- end }}