apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  {{- if not .Values.reloadly.ingress.enabled }}
  type: {{ .Values.reloadly.accountApp.service.type }}
  {{- end }}
  selector:
    app: account-service
  ports:
    - port: 8080
      targetPort: 8080
      {{- if not .Values.reloadly.ingress.enabled }}
      nodePort: 30080
      {{- end }}