apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  {{- if not .Values.reloadly.ingress.enabled }}
  type: {{ .Values.reloadly.authApp.service.type }}
  {{- end }}
  selector:
    app: authentication-service
  ports:
    - port: 9090
      targetPort: 9090
      {{- if not .Values.reloadly.ingress.enabled }}
      nodePort: 30090
      {{- end }}