--
-- Accounts table.
--
CREATE TABLE account_table
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    account_id VARCHAR(40)                             NOT NULL UNIQUE,
    active     BOOLEAN DEFAULT true
);