[[components]]
== Reloadly Modules

Foundational modules are reusable pieces of software that can be easily integrated into other modules.
The following modules are used in the rest of the platform.
Note that, in a Microservices architecture, individual microservices should share reusable code only if it makes sense and if sharable code is well managed by a team which keeps pace with others.

=== Email

This module supports email sending facilities.
This is a drop-in solution.
Add the following dependency in any Spring Boot application and Spring Boot Auto-configuration would wire the necessary beans.

[source,xml]
----
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>email-integration</artifactId>
    <version>1.2.0</version>
</dependency>
----

This component is configurable. See the configuration properties of this module.

=== SMS

This module supports SMS sending facilities. This is a drop-in solution.
Add the following dependency in any Spring Boot application and Spring Boot Auto-configuration would wire the necessary beans.

[source,xml]
----
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>sms-integration</artifactId>
    <version>1.2.0</version>
</dependency>
----

This component is configurable. See the configuration properties of this module.

=== Security Integration

This module automatically secures all Web API endpoints with Auth Service security via Spring Security.
This is a drop-in solution.
Add the following dependency in any Spring Boot application and Spring Boot Auto-configuration would wire the necessary beans.

[source,xml]
----
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>security-integration</artifactId>
    <version>1.2.0</version>
</dependency>
----

This component is configurable. See the configuration properties of this module.

=== Notification Integration

This module integrates Notification Service via a Java API. The Java API wraps the Notification Service REST API calls.
This is a drop-in solution.
Add the following dependency in any Spring Boot application and Spring Boot Auto-configuration would wire the necessary beans.

[source,xml]
----
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>notification-integration</artifactId>
    <version>1.2.0</version>
</dependency>
----

This component is configurable. See the configuration properties of this module.

=== Swagger UI Integration

This module adds Swagger UI integration to any Spring Boot app.
This is a drop-in solution.
Add the following dependency in any Spring Boot application and Spring Boot Auto-configuration would wire the necessary beans.

[source,xml]
----
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>swagger-ui-integration</artifactId>
    <version>1.2.0</version>
</dependency>
----

This component is configurable. See the configuration properties of this module.