[[production-deployment]]
== Production Deployment

The individual microservices may be run as standalone spring boot applications in lower environments.
However, for production like environments, where HA, failover and scalability needs exist, a suitable approach may be taken.
We discuss some aspects and approaches below.

=== Kubernetes Deployment (EKS)

See this GitHub https://github.com/arunkpatra/reloadly-services/issues/17[issue].

See the  <<kubernetes-deployment, Kubernetes Deployment>> chapter for more details.

Kubernetes would be the ideal way to run and scale the microservices of this platform.
Of special interest is the transaction processor which necessarily needs to scale based on transaction volumes.
Some aspects to note are:

* It's best to keep databases outside the scope of Kubernetes.
Consider having a managed database service from a cloud provider like AWS or GCP.
* Microservices including the transaction processor should be Dockerized and docker images should be created in the build pipeline.
Store images in an organizational Docker Registry or a hosted one.
* Consider a managed Kubernetes Service like Amazon EKS of Google GKE.

==== Docker Images

To create Docker images, follow these steps. First install Docker Desktop for macOS.

----
cd account-service
docker build --tag reloadly/account-service .
----

To spin up a container, issue the following command. First start your MySQL instance on your local machine and ensure that the tables are created.

----
docker run -it -p 8080:8080 --rm --env DB_USER=root --env DB_PASSWORD=mysqlpass123 --env DB_URL=jdbc:mysql://host.docker.internal:3306/rlacctdb reloadly/account-service:latest env
----

To launch in the background:

----
docker run -d -p 8080:8080 --rm --env DB_USER=root --env DB_PASSWORD=mysqlpass123 --env DB_URL=jdbc:mysql://host.docker.internal:3306/rlacctdb reloadly/account-service:latest env
----

You can also run the following from the project root. It will create Docker images for all the microservices contained in this project.

----
mvn clean install -Pdocker
----

[NOTE]
====
For the above to work, you must have Docker running locally on your machine, and the Docker Registry running locally at port 5000. See https://docs.docker.com/registry/deploying/[this] to run a local Docker Registry.
====

Upon successful of the above command, you would have the required Docker Images installed into your locally running Docker Registry, with the images tagged as `localhost:5000/com.reloadly/<artifactId>:<versionId>`, where:

* <artifactId> is the maven artifact ID of the microservice.
* <versionId> is the maven version of the microservice.

As an example, the Account microservice image would be named as `localhost:5000/com.reloadly/account-service:1.1.0`. You could thus do a `docker pull localhost:5000/com.reloadly/account-service:1.1.0`. You could use these images to run Kubernetes containers or in your Helm Charts.

==== Helm Charts

As a best practice, consider using Helm Charts to easily manage deployments and deployment environments.
It's beneficial to use Helm Charts since it allows for easy rollback.

==== Service Mesh

Consider using https://istio.io/[Istio] or https://linkerd.io/[Linkerd] as a service mesh. This would allow you to handle load balancing, retries and TLS offloading.

==== Distributed Tracing

Consider using https://www.jaegertracing.io/[Jaeger] for distributed tracing. This should serve as a very useful tool in a microservices context.

=== AWS Beanstalk or EC2 Containers

While deployment to AWS Beanstalk or EC2 containers is possible, it should probably make sense only for small deployments.
Managing these environments is fraught with errors and do not support automation very well.
For modern microservice deployment strategies, consider using Helm Charts and Kubernetes.



